%macro corr_ctc(data=, var1=, var2=, out=);
proc corr data =&data SPEARMAN;
var &var2 &var1;
ods output SpearmanCorr=S(where=(Variable in ("&var2")));
run;
data &out;
set S;
length varN $20. Coef 6.2  Pvalue 4.2 ;
varN="&var1";
Coef=&var1;
Pvalue=p&var1;
keep varN Coef Pvalue;
run;
%mend;

%macro corr_sum(Dp=,var_c=,out=,coefname=,pname=);
%corr_ctc(data=&Dp, var1=n_tmdsc, var2=&var_c, out=i1);
%corr_ctc(data=&Dp, var1=n_gmdsc, var2=&var_c, out=i2);
%corr_ctc(data=&Dp, var1=n_mmdsc, var2=&var_c, out=i3);
%corr_ctc(data=&Dp, var1=n_lmdsc, var2=&var_c, out=i4);
data &out; set i1-i4;&coefname=Coef;&pname=Pvalue;run;
%mend;
